name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      # - name: Generate Prisma client
      #   run: npx prisma generate

      # - name: Apply Prisma migrations
      #   run: npx prisma migrate deploy --preview-feature

      - name: Build application
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-project-id: discord
        scope: udit-sharmas-projects-c1c1f56a

